### ISSUE TITLE
How to create a HTMLType Column?

### ISSUE THREAD

**Issue by dheerajwebkul** [friends-of-prestashop/demo-cqrs-hooks-usage-module#3]
Can not see html type class here:
https://github.com/PrestaShop/PrestaShop/tree/1.7.6.0/src/Core/Grid/Column/Type/Common

Like this,
![download (6)](https://user-images.githubusercontent.com/19220745/61117174-96589600-a4b3-11e9-81da-2d543ac070a3.png)

**Comment by tomas862** [comment]
Hi @dheerajwebkul 

I would suggest to create new column type in your module. Name it like `AssignUserColumn`.

if using `demo-cqrs-hooks-usage-module` the steps are:

1. Create AssignUserColumn class

```php
<?php
// modules/ps_democqrshooksusage/src/Grid/Column/AssignUserColumn.php
namespace DemoCQRSHooksUsage\Grid\Column;

use PrestaShop\PrestaShop\Core\Grid\Column\AbstractColumn;

final class AssignUserColumn extends AbstractColumn
{
    /**
     * {@inheritdoc}
     */
    public function getType()
    {
        return 'ps_democqrshooksusage_assign_user';
    }
}
```

note that the directory structure is very important here

2. Create template and name it `ps_democqrshooksusage_assign_user.twig.html` ( again directory structure is very important here) the name should match the type

directory is: `views/PrestaShop/Admin/Common/Grid/Columns/Content/ps_democqrshooksusage_assign_user.html.twig`

```html

{# modules/ps_democqrshooksusage/views/PrestaShop/Admin/Common/Grid/Columns/Content/ps_democqrshooksusage_assign_user.html.twig #}
<div>
  <button>My button</button>
</div>
```

3. Use it in hook
```php
public function hookActionCustomerGridDefinitionModifier(array $params)
    {
        /** @var GridDefinitionInterface $definition */
        $definition = $params['definition'];

        $translator = $this->getTranslator();

        $definition
            ->getColumns()
            ->addAfter(
                'optin',
                (new AssignUserColumn('is_allowed_for_review'))
                    ->setName($translator->trans('Assign user', [], 'Modules.Democqrshooksusage.Admin'))
            )
        ;

        $definition->getFilters()->add(
            (new Filter('is_allowed_for_review', YesAndNoChoiceType::class))
            ->setAssociatedColumn('is_allowed_for_review')
        );
    }
```

4. Result

![button](https://user-images.githubusercontent.com/17051250/61121193-44117800-a4a7-11e9-8982-c55ff05c8384.png)


more information about grid component can be found here https://devdocs.prestashop.com/1.7/development/components/grid/

**Comment by dheerajwebkul** [comment]
@tomas862 Thank you so much.

Its working.

I have one more query regarding new module structure. We have to run this command always if working with src/ folder.

$ composer dumpautoload

So if I am providing the module zip folder to client and client will upload the module zip with module page.

So how the client will run this command, Is this not done by installing the module any way?

Thanks,

**Comment by tomas862** [comment]
since the composer is package manager and  only in rare cases it is available on production servers I would recommend for you to send the client zip with all vendor folder already compiled - so just run `composer install` and create the zip of whole folder.

**Comment by dheerajwebkul** [comment]
@tomas862 
Yes, Its the way.
But I thought is vender have large data so its not good to zip all.

But yes, in this case, vender have minimal autoloads and it can be sent to the client.

Thanks for your help @tomas862 .

**Comment by tomas862** [comment]
no problem @dheerajwebkul 
don't forget that for production you can use `composer install --no-dev --optimize-autoloader` which reduces the size of vendor if you have for instance unit tests.

**Comment by dheerajwebkul** [comment]
@tomas862 Yes sure, thanks.
