### ISSUE TITLE
how to add new column with not sql

### ISSUE THREAD

**Issue by langziyang** [friends-of-prestashop/demo-cqrs-hooks-usage-module#5]
if i want add new column only do something,not came form sql,how to do that? like action but display column

**Comment by sarjon** [comment]
Hi, you could try using `'action{GridId}GridDataModifier'` hook for this, let me know if it works. :)

**Comment by langziyang** [comment]
> Hi, you could try using `'action{GridId}GridDataModifier'` hook for this, let me know if it works. :)

thank you,this function can get records,but i do not know how to do that.

i mean,i want add colum, put a button,when click this button,ajax get other data form current records.

**Comment by tomas862** [comment]
Hi @langziyang - I think I helped to solve similar issue here https://github.com/friends-of-presta/demo-cqrs-hooks-usage-module/issues/3#issuecomment-510874947. Let me know if it helps as well :)

**Comment by langziyang** [comment]
> Hi @langziyang - I think I helped to solve similar issue here [#3 (comment)](https://github.com/friends-of-presta/demo-cqrs-hooks-usage-module/issues/3#issuecomment-510874947). Let me know if it helps as well :)

thank you ,this is i want!
